language: node_js

script:
  - "npm run travis"

node_js:
  - "14"
  - "12"
  - "10"

branches:
  except:
    - /^v\d+\./

matrix:
  fast_finish: true
  include:
    - node_js: "14"
      env: COVERAGE=true
  allow_failures:
    - env: COVERAGE=true

sudo: false
